### ISSUE TITLE
Error in crypto.createDecipheriv

### ISSUE THREAD

**Issue by truongthaison** [takayukii/example-Laravelchat-Socket.io#1]
Hi,
I encountered an error with Laravel 5.6.

please help me

**Comment by takayukii** [comment]
@Vagabondtq 

Sorry, unfortunateIy I am not doing Laravel work recently. I can't help. 

I created different version of chat example before. Hope it would help.

https://github.com/takayukii/example-laravelchat-echo-socket.io
